//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SerialPortTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SERIALPORT_DIALOG           102
#define IDS_UPDATE_STR                  102
#define IDR_MAINFRAME                   128
#define IDD_WATCH_ATTRI                 132
#define IDD_DIALOG1                     134
#define IDB_FACE_HAPPY                  143
#define IDB_FACE_SAD                    144
#define IDB_WALI                        149
#define IDC_SERIALPORT_NUM              1000
#define IDC_BAUD_RATE                   1001
#define IDC_DATA_BIT                    1002
#define IDC_STOP_BIT                    1003
#define IDC_CHECK_BIT                   1004
#define IDC_OPEN_SERIALPORT             1007
#define IDC_RECV_BUF                    1008
#define IDC_SEND_BUF                    1009
#define IDC_ENDIAN                      1010
#define IDC_RTS_FLOW                    1011
#define IDC_G_CYCLE_SEND                1013
#define IDC_GHEX_SEND                   1014
#define IDC_AUTO_SEND                   1015
#define IDC_CYCLE_TIME                  1016
#define IDC_SELECT_ALL                  1017
#define IDC_EMPTY_SENDBUF               1018
#define IDC_HEX_SEND                    1019
#define IDC_HEX_DIS                     1020
#define IDC_CHECK_SUM                   1021
#define IDC_CHECK_CRC16_IBM             1022
#define IDC_CHECK_CRC16_CCITT           1023
#define IDC_CHECK_CRC32                 1024
#define IDC_CHECK_XOR                   1025
#define IDC_STOP_DIS                    1026
#define IDC_AUTOSEND_TIME               1027
#define IDC_MANUAL_SEND                 1028
#define IDC_CHECK_INDEX                 1029
#define IDC_EMPTY_RECVBUF               1030
#define IDC_SPIN2                       1031
#define IDC_ABOUT                       1032
#define IDC_B_CONNECTED                 1033
#define IDC_SERIALPORT_STATE            1034
#define IDC_SEND_COUNT                  1035
#define IDC_RECV_COUNT                  1036
#define IDC_SYS_TIME                    1037
#define IDC_LOGO                        1038
#define IDC_USE_WATCHES                 1039
#define IDC_HIDE_SEND                   1040
#define IDC_NEW_LINE_END                1041
#define IDC_REFRESH_COMM                1042
#define IDC_UPDATE_CONTENT              1043
#define IDC_OK                          1044
#define IDC_RAUTO_EN                    1045
#define IDC_ERAUTO_EDIT                 1046
#define IDC_SAUTOBOX                    1047
#define IDC_SUFFIX                      1048
#define IDC_CHECK_SUFFIX                1049
#define IDC_OFFSET                      1050
#define IDC_DATA_TYPE                   1051
#define IDC_B_HEX                       1052
#define IDC_SPIN1                       1053
#define IDC_HIST                        1054
#define IDC_WATCH1                      1101
#define IDC_WATCH2                      1102
#define IDC_WATCH3                      1103
#define IDC_WATCH4                      1104
#define IDC_WATCH5                      1105
#define IDC_WATCH6                      1106
#define IDC_WATCH7                      1107
#define IDC_WATCH8                      1108
#define IDC_WATCH_BTN1                  1151
#define IDC_WATCH_BTN2                  1152
#define IDC_WATCH_BTN3                  1153
#define IDC_WATCH_BTN4                  1154
#define IDC_WATCH_BTN5                  1155
#define IDC_WATCH_BTN6                  1156
#define IDC_WATCH_BTN7                  1157
#define IDC_WATCH_BTN8                  1158
#define IDC_SEND_MEM1                   1201
#define IDC_SEND_MEM2                   1202
#define IDC_SEND_MEM3                   1203
#define IDC_SEND_MEM4                   1204
#define IDC_SEND_MEM5                   1205
#define IDC_SEND_MEM6                   1206
#define IDC_SEND_MEM7                   1207
#define IDC_SEND_MEM8                   1208
#define IDC_SEND_MEM9                   1209
#define IDC_SEND_MEM10                  1210
#define IDC_SEND_MEM11                  1211
#define IDC_SEND_MEM12                  1212
#define IDC_SEND_MEM13                  1213
#define IDC_SEND_MEM14                  1214
#define IDC_MEM_1                       1251
#define IDC_MEM_2                       1252
#define IDC_MEM_3                       1253
#define IDC_MEM_4                       1254
#define IDC_MEM_5                       1255
#define IDC_MEM_6                       1256
#define IDC_MEM_7                       1257
#define IDC_MEM_8                       1258
#define IDC_MEM_9                       1259
#define IDC_MEM_10                      1260
#define IDC_MEM_11                      1261
#define IDC_MEM_12                      1262
#define IDC_MEM_13                      1263
#define IDC_MEM_14                      1264
#define IDC_CHECK_MEM1                  1301
#define IDC_CHECK_MEM2                  1302
#define IDC_CHECK_MEM3                  1303
#define IDC_CHECK_MEM4                  1304
#define IDC_CHECK_MEM5                  1305
#define IDC_CHECK_MEM6                  1306
#define IDC_CHECK_MEM7                  1307
#define IDC_CHECK_MEM8                  1308
#define IDC_CHECK_MEM9                  1309
#define IDC_CHECK_MEM10                 1310
#define IDC_CHECK_MEM11                 1311
#define IDC_CHECK_MEM12                 1312
#define IDC_CHECK_MEM13                 1313
#define IDC_CHECK_MEM14                 1314
#define IDC_BUTTON1                     2000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
